task_management/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from core.views import home, no_permission

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('task/', include("tasks.urls")),
    path('users/', include("users.urls")),
    path('no-permission/', no_permission, name='no-permission')
]+ debug_toolbar_urls()

tasks/urls.py
from django.urls import path
from tasks.views import employee_dashboard, manager_dashboard, create_task, view_task, update_task,delete_task

urlpatterns = [
    path('user-dashboard/', employee_dashboard),
    path('manager-dashboard/',manager_dashboard, name='manager-dashboard'),
    path('create-task/', create_task, name='create-task'),
    path('view-task/', view_task),
    path('update-task/<int:id>/', update_task, name='update-task'),
    path('delete-task/<int:id>/', delete_task, name='delete-task')
]

tasks/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    # tasks

    def __str__(self):
        return self.name

class Task(models.Model):
    STATUS_CHOICES = [
        ('PENDING','Pending'),
        ('IN PROGRESS','In Progress'),
        ('COMPLETED','Completed')
    ]
    assigned_to = models.ManyToManyField(Employee,related_name='tasks')
    project = models.ForeignKey("Project", on_delete = models.CASCADE, default=1, related_name='allTask')
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDIGN')
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # details

    def __str__(self):
        return self.title


# One to One ---> This Example is out of this project ---> Ekta Student er Ektai Student_profile ase
                            # One to One : models.OneToOneField()
# One to Many ---> Ekta project e onekgula task thakte pare:
                            # One to Many : models.ForenignKey()
# Many to Many ---> Ekta Task onek Employee korte pare, Abar Ekta Employee Onekgula Task Korte pare


class Task_detail(models.Model):
    HIGH = 'H'
    MEDIUM = 'M'
    LOW = 'L'
    PRIORITY_CHOICE = (
        (HIGH,'High'),
        (MEDIUM,'Medium'),
        (LOW,'Low')
    )
    task = models.OneToOneField(Task, on_delete=models.CASCADE, related_name='details')
    # assigned_to = models.CharField(max_length=200)
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICE, default=LOW)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Details for Task {self.task.title}"


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    # allTask

    def __str__(self):
        return self.name
    





tasks/forms.py
from django import forms
from tasks.models import Task, Task_detail

# django Form

class TaskForm(forms.Form):
    title = forms.CharField(max_length=250, label='Task Title')
    description = forms.CharField(widget=forms.Textarea, label='Task Description')
    due_date = forms.DateField(widget=forms.SelectDateWidget, label='Due Date')
    assigned_to = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, label='Assigned To', choices=[])


    def __init__(self, *args, **kwargs):
        # print(args,kwargs)
        employees = kwargs.pop('employees',[])
        # print(employees)
        super().__init__(*args, **kwargs)
        self.fields['assigned_to'].choices = [(emp.id, emp.name) for emp in employees]


class StyledFormMixin:
    '''Mixing to apply style to form field'''

    default_classes = "border-2 border-blue-900 rounded-md p-2 w-full"

    def apply_style_widgets(self):
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.TextInput):
                field.widget.attrs.update({
                    'class': self.default_classes,
                    'placeholder': f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({
                    'class': self.default_classes,
                    'placeholder': f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget, forms.SelectDateWidget):
                field.widget.attrs.update({
                    'class': "border-2 border-gray-300 rounded-md"
                })
            elif isinstance(field.widget, forms.CheckboxSelectMultiple):
                field.widget.attrs.update({
                    'class': "space-y-2"
                })




# django Model Form
class TaskModelForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','description','due_date','assigned_to']

        widgets = {
            'due_date': forms.SelectDateWidget(),
            'assigned_to': forms.CheckboxSelectMultiple()
        }


        '''Menual widget'''
        # widgets = {
        #     'title': forms.TextInput(attrs={
        #         'class': "border-2 border-gray-300 rounded-md p-2 w-full h-96", 'placeholder': "Task Title"
        #     }),
        #     'description': forms.Textarea(attrs={
        #         'class': "border-2 border-gray-300 rounded-md w-full h-32", 'placeholder': "Task Description"
        #     }),
        #     'due_date':forms.SelectDateWidget(attrs={
        #         'class': "border-2 border-gray-300 rounded-md"
        #     }),
        #     'assigned_to':forms.CheckboxSelectMultiple(attrs={
        #         'class': "space-y-2"
        #     })
        # }

    '''Using Mixing Widget'''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.apply_style_widgets()
        

class Task_detailModelform(StyledFormMixin,forms.ModelForm):
    class Meta:
        model = Task_detail
        fields = ['priority', 'notes']

    '''Using Mixing Widget'''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.apply_style_widgets()

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tasks.forms import TaskForm, TaskModelForm, Task_detailModelform
from tasks.models import Employee, Task, Task_detail, Project
from datetime import date
from django.db.models import Q, Count, Max, Min, Sum, Avg
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required

# Create your views here.
# -------------------------

def is_manager(user):
    return user.groups.filter(name='Manager').exists()

def is_employee(user):
    return user.groups.filter(name='Employee').exists()

# -------------------------
@user_passes_test(is_employee, login_url='no-permission')
def employee_dashboard(request):
    return render(request, "dashboard/employee_dashboard.html")

@user_passes_test(is_manager, login_url='no-permission')
def manager_dashboard(request):
    
    # getting task count
    # total_task = tasks.count()
    # completed_task = Task.objects.filter(status="COMPLETED").count()
    # in_progress_task = Task.objects.filter(status="IN_PROGRESS").count()
    # pending_task = Task.objects.filter(status="PENDING").count()

    # counts = {
    #     "total":total_task,
    #     "completed":completed_task,
    #     "progress":in_progress_task,
    #     "pending":pending_task
    # }
    type = request.GET.get('type','all')
    
    base_query = Task.objects.select_related('details').prefetch_related('assigned_to')
    
    if type=='complete':
        tasks = base_query.filter(status="COMPLETED")
    elif type == 'in_progress':
        tasks = base_query.filter(status="IN_PROGRESS")
    elif type == 'pending':
        tasks = base_query.filter(status="PENDING")
    elif type == 'all':
        tasks = base_query.all()
    

    counts = Task.objects.aggregate(
        total = Count('id'),
        completed = Count('id', filter=Q(status="COMPLETED")),
        in_progress = Count('id', filter=Q(status="IN_PROGRESS")),
        pending = Count('id', filter=Q(status="PENDING"))
    )

    context = {
        "tasks":tasks,
        "counts":counts
    }

    return render(request, "dashboard/manager_dashboard.html",context)


@login_required
@permission_required("tasks.add_task", login_url='no-permission')
def create_task(request):

    task_form = TaskModelForm()
    task_detail_form = Task_detailModelform()

    if request.method=='POST':
        task_form = TaskModelForm(request.POST)
        task_detail_form = Task_detailModelform(request.POST)

        if task_form.is_valid() and task_detail_form.is_valid():

            '''For django Model Form'''

            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()

            messages.success(request, "Created Task Successfully")
            return redirect("create-task")


    context = {"task_form":task_form, "task_detail_form":task_detail_form}
    return render(request, "taskForm.html",context)



@login_required
@permission_required("tasks.change_task", login_url='no-permission')
def update_task(request, id):

    task = Task.objects.get(id=id)

    task_form = TaskModelForm(instance=task)
    if task.details:
        task_detail_form = Task_detailModelform(instance=task.details)

    if request.method=='POST':
        task_form = TaskModelForm(request.POST, instance=task)
        task_detail_form = Task_detailModelform(request.POST, instance=task.details)

        if task_form.is_valid() and task_detail_form.is_valid():

            '''For django Model Form'''

            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()

            messages.success(request, "Task Update Successfully")
            return redirect("update-task", id)


    context = {"task_form":task_form, "task_detail_form":task_detail_form}
    return render(request, "taskForm.html",context)


@login_required
@permission_required("tasks.delete_task", login_url='no-permission')
def delete_task(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.delete()
        messages.success(request, 'Task Deleted Successfully')
        return redirect('manager-dashboard')
    else:
        messages.error(request, 'Something went wrong')
        return redirect('manager-dashboard')

@login_required
@permission_required("tasks.view_task", login_url='no-permission')
def view_task(request):
    # tasks = Task.objects.all()
    # tasks = Task.objects.filter(status="PENDING")
    # tasks = Task.objects.filter(due_date=date.today())
    # tasks = Task_detail.objects.exclude(priority="L")
    # tasks = Task.objects.filter(id__gt=5)
    # tasks = Task.objects.filter(title__contains="paper")
    # tasks = Task_detail.objects.select_related('task').all()
    # tasks = Task.objects.filter(description__icontains = "c", status = "PENDING") '''AND Operation'''
    # tasks = Task.objects.filter(Q(status="PENDING") | Q(status="IN_PROGRESS"))
    # tasks = Task.objects.select_related('project').all()
    # tasks = Task.objects.select_related('details').all()
    # tasks = Task_detail.objects.select_related('task').all()
    # tasks = Task_detail.objects.select_related('task').all()
    # projects = Project.objects.prefetch_related('allTask').all()
    # countTask = Task.objects.aggregate(num_count= Count("id"))

    # projects = Project.objects.annotate(num_task = Count("allTask")).order_by("id")
    # emps = Employee.objects.prefetch_related("tasks").all()

    # projects = Project.objects.prefetch_related("allTask").all()
    # tasks = Task.objects.filter(due_date = date.today()).all()
    # emps = Employee.objects.prefetch_related("tasks").all()
    tasks = Task.objects.select_related("details").all()
    # recent_task = Task.objects.order_by('-created_at').first()
    

    return render(request,"view_task.html",{"tasks":tasks})

tasks/templates/dashboard/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Italianno&display=swap" rel="stylesheet">
		{% comment %} Tailwind css  {% endcomment %}
		<link rel="stylesheet" href="{% static 'css/output.css' %}">

		<title>{% block title %}{% endblock title %}</title>

		<style>
			body{
				font-family: "Inter",sans-serif;
			}
		</style>
	</head>
	<body class="p-6 bg-gray-100">
		<header class="max-w-[1400px] mx-auto">
			<div class="flex justify-between">
				<div>
					<h1 class="text-xl font-semibold">Dashboard</h1>
				</div>
				<div class="flex">
					<button class="p-2 bg-white-400 rounded-full hover:bg-gray-200 cursor-pointer">
						<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
							<path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0M3.124 7.5A8.969 8.969 0 0 1 5.292 3m13.416 0a8.969 8.969 0 0 1 2.168 4.5" />
						  </svg>						  
					</button>
					<button class="font-semibold bg-blue-500 rounded-full text-white flex justify-center items-center w-10 h-10 hover:cursor-pointer">B</button>
				</div>
			</div>
		</header>
		<main class="max-w-[1400px] mx-auto mt-9">
            
			{% comment %} CARD SECTION {% endcomment %}
			<section class="grid grid-cols-4 gap-6">
				<a href="{% url 'manager-dashboard' %}">
					<div class="rounded-md p-2 bg-white shadow-md">
						<h3 class="text-sm font-medium text-gray-500 mb-3">TOTAL TASK</h3>
						<div class="flex justify-between">
							<div>
								<h1 class="text-2xl font-semibold">{{counts.total}}</h1>
								<p class="text-sm text-gray-500 mt-2">11 last month</p>
							</div>
							<div class="bg-blue-100 rounded-full flex justify-center h-10 p-2">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-blue-800">
									<path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
								</svg>
							</div>
						</div>
					</div>
				</a>
				<a href="{% url 'manager-dashboard' %}?type=complete">
					<div class="rounded-md p-2 bg-white shadow-md">
						<h3 class="text-sm font-medium text-gray-500 mb-3">COMPLETED TASK</h3>
						<div class="flex justify-between">
							<div>
								<h1 class="text-2xl font-semibold">{{counts.completed}}</h1>
								<p class="text-sm text-gray-500 mt-2">10 last month</p>
							</div>
							<div class="bg-green-100 rounded-full flex justify-center h-10 p-2">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-green-800">
									<path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
								</svg>
							</div>
						</div>
					</div>
				</a>
				<a href="{% url 'manager-dashboard' %}?type=in_progress">
					<div class="rounded-md p-2 bg-white shadow-md">
						<h3 class="text-sm font-medium text-gray-500 mb-3">TASK IN PROGRESS</h3>
						<div class="flex justify-between">
							<div>
								<h1 class="text-2xl font-semibold">{{counts.in_progress}}</h1>
								<p class="text-sm text-gray-500 mt-2">8 last month</p>
							</div>
							<div class="bg-yellow-100 rounded-full flex justify-center h-10 p-2">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-yellow-500">
									<path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
								  </svg> 
							</div>
						</div>
					</div>
				</a>
				<a href="{% url 'manager-dashboard' %}?type=pending">
					<div class="rounded-md p-2 bg-white shadow-md">
						<h3 class="text-sm font-medium text-gray-500 mb-3">TODOS</h3>
						<div class="flex justify-between">
							<div>
								<h1 class="text-2xl font-semibold">{{counts.pending}}</h1>
								<p class="text-sm text-gray-500 mt-2">11 last month</p>
							</div>
							<div class="bg-rose-100 rounded-full flex justify-center h-10 p-2">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-rose-500">
									<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m.75 12 3 3m0 0 3-3m-3 3v-6m-1.5-9H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
								  </svg>							  
							</div>
						</div>
					</div>
				</a>
				
			</section>

			<div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="px-2 py-1 {% if message.tags == 'success' %}bg-green-500{% endif %}">{{ message }}</div>
                    {% endfor %}
                {% endif %}

            </div>

            {% block tasks %}

            {% endblock tasks %}

		</main>
        {% include "footer.html" %}
	</body>
</html>

tasks/templates/dashboard/employee_dashboard.html
{% extends "dashboard/dashboard.html" %}

{% block title %}User dashboard{% endblock title %}

{% block tasks %}
         {% comment %} Table Section {% endcomment %}
         <section class="mt-10 grid grid-cols-1 gap-6 md:grid-cols-1 lg:grid-cols-2">
            {% comment %} Table One  {% endcomment %}
            <div class="bg-white rounded-md shadow-md ">
                <h1 class="p-4 text-lg font-semibold">Today's Tasks</h1>
                <div class="flex justify-between">
                    <div class="p-3 flex">
                        <div class="h-2 w-2 bg-blue-500 rounded-full mr-2 mt-2"></div>
                        <h3>Complete project proposal</h3>
                    </div>
                    <div>
                        <p class="text-sm font-medium text-gray-500 p-2">High</p>
                    </div>
                </div>
                <div class="flex justify-between">
                    <div class="p-3 flex">
                        <div class="h-2 w-2 bg-green-500 rounded-full mr-2 mt-2"></div>
                        <h3>Review team updates</h3>
                    </div>
                    <div>
                        <p class="text-sm font-medium text-gray-500 p-2">Medium</p>
                    </div>
                </div>
                <div class="flex justify-between">
                    <div class="p-3 flex">
                        <div class="h-2 w-2 bg-red-500 rounded-full mr-2 mt-2"></div>
                        <h3>Prepare for client metting</h3>
                    </div>
                    <div>
                        <p class="text-sm font-medium text-gray-500 p-2">Low</p>
                    </div>
                </div>
            </div>
            {% comment %} Table Two  {% endcomment %}
            <div class="bg-white rounded-md shadow-md">
                {% comment %} Table Heading  {% endcomment %}
                 <h1 class="p-4 text-lg font-semibold">All Tasks</h1>
                <div class="grid grid-cols-4 p-3 text-sm font-medium text-gray-500">
                    <h2>TASK TITLE</h2>
                    <h2>PRIORITY</h2>
                    <h2>TEAM</h2>
                    <h2>CREATED AT</h2>
                </div>
                {% comment %} Table Items  {% endcomment %}
                <div class="grid grid-cols-4">
                    <div class="p-3 flex">
                        <div class="h-2 w-2 bg-blue-500 rounded-full mr-2 mt-2"></div>
                        <h3>Test Low Task</h3>
                    </div>
                    <div class="mt-3">
                        <span class="bg-blue-100 px-3 py-1 rounded-full text-sm font-semibold text-blue-800">Low</span>
                    </div>
                    <div class="flex -space-x-2 mt-2">
                        <div class="w-8 h-8 rounded-full bg-blue-500 text-white flex justify-center items-center border-2 border-white">CA</div>
                        
                        <div class="w-8 h-8 rounded-full bg-green-500 text-white flex justify-center items-center border-2 border-white">JS</div>
                        
                        <div class="w-8 h-8 rounded-full bg-yellow-500 text-white flex justify-center items-center border-2 border-white">B</div>
                        
                    </div>
                    <div>
                        <h4 class="text-gray-500 mt-3">9 months ago</h4>
                    </div>
                </div>
                <div class="grid grid-cols-4">
                    <div class="p-3 flex">
                        <div class="h-2 w-2 bg-green-500 rounded-full mr-2 mt-2"></div>
                        <h3>Test Task</h3>
                    </div>
                    <div class="mt-3">
                        <span class="bg-green-100 px-3 py-1 rounded-full text-sm font-semibold text-green-800">Medium</span>
                    </div>
                    <div class="flex -space-x-2 mt-2">
                        <div class="w-8 h-8 rounded-full bg-rose-500 text-white flex justify-center items-center border-2 border-white">CA</div>
                        
                        <div class="w-8 h-8 rounded-full bg-fuchsia-500 text-white flex justify-center items-center border-2 border-white">JS</div>
                        
                        <div class="w-8 h-8 rounded-full bg-sky-400 text-white flex justify-center items-center border-2 border-white">B</div>
                        
                    </div>
                    <div>
                        <h4 class="text-gray-500 mt-3">11 months ago</h4>
                    </div>
                </div>
                <div class="grid grid-cols-4">
                    <div class="p-3 flex">
                        <div class="h-2 w-2 bg-rose-500 rounded-full mr-2 mt-2"></div>
                        <h3>Test Task</h3>
                    </div>
                    <div class="mt-3">
                        <span class="bg-rose-100 px-3 py-1 rounded-full text-sm font-semibold text-rose-800">High</span>
                    </div>
                    <div class="flex -space-x-2 mt-2">
                        <div class="w-8 h-8 rounded-full bg-orange-500 text-white flex justify-center items-center border-2 border-white">CA</div>
                        
                        <div class="w-8 h-8 rounded-full bg-red-400 text-white flex justify-center items-center border-2 border-white">EV</div>
                        
                        <div class="w-8 h-8 rounded-full bg-yellow-500 text-white flex justify-center items-center border-2 border-white">B</div>
                        
                    </div>
                    <div>
                        <h4 class="text-gray-500 mt-3">10 months ago</h4>
                    </div>
                </div>
                
            </div>
            
         </section>

{% endblock tasks %}

tasks/templates/dashboard/manager_dashboard.html
{% extends "dashboard/dashboard.html" %}

{% block title %}Manager dashboard{% endblock title %}

{% block tasks %}

			{% comment %} Table Section  {% endcomment %}
			<section class="mt-10 divide-y-1 divide-gray-200 bg-white shadow-md rounded-md">
				<!-- TABLE HEADING -->
				<div class="grid grid-cols-4 p-3 text-sm font-medium text-gray-500">
					<h3>TASK TITLE</h3>
					<h3>PRIORITY</h3>
					<h3>TEAM</h3>
					<h3>CREATED AT</h3>
				</div>
				{% comment %} Table Items {% endcomment %}
				
				{% for task in tasks %}
					<div class="grid grid-cols-4 p-3">
						<div class="flex">
							<div class="w-2 h-2 bg-violet-500 rounded-full mt-2 mr-2"></div>
							<h3>{{task}}</h3>
							<div>
								<a href="{% url 'update-task' task.id %}" class="px-2 bg-green-500">Edit</a>
							</div>
							<div>
								<form action="{% url 'delete-task' task.id %}" method="POST">
									{% csrf_token %}
									<button type="submit" class="bg-rose-500">Delete</button>
								</form>
							</div>
						</div>
						<div>
							<span class="px-3 py-1 text-sm font-semibold bg-blue-100 rounded-full text-blue-800">{{task.details.get_priority_display}}</span>
						</div>
						<div class="flex -space-x-2">
							{% for emp in task.assigned_to.all %}
							<div class="w-8 h-8 rounded-full bg-blue-800 text-white flex justify-center items-center border-2 border-white">{{emp.name | slice:':2'}}</div>
							{% endfor %}
						</div>
						<div>
							<h4 class="text-gray-500">{{task.created_at|timesince}}</h4>
						</div>
					</div>
				{% endfor %}
				
		
			</section>

{% endblock tasks %}